# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
                ('album_title', models.CharField(max_length=255)),
                ('album_description', models.CharField(max_length=255)),
                ('album_logo', models.FileField(upload_to='album/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='video/%Y/%m/%d')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoApp.Album')),
            ],
        ),
    ]
